services:
  front-end:
    build:
      context: .
      args:
        - VITE_API_HOST=localhost:3001
    environment:
      NODE_ENV: production
    ports:
      - 80:80

  back-end:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      APP_NAME: 2048-Backend
      APP_PORT: 3001
      APP_ROUTE_PREFIX: /api
      GROQ_API_KEY: GROQ_API_KEY
    ports:
      - 3001:3001

