services:
  front-end:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 80:80

  back-end:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      APP_NAME: 2048-Backend
      APP_PORT: 3001
      APP_ROUTE_PREFIX: /api
      GROQ_API_KEY: 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
    ports:
      - 3001:3001

